### ISSUE TITLE
`.idea/misc.xml`を修正

### ISSUE THREAD

**Issue by Mitsuki4123** [Sereno-Anan/SerenoAndroidApp#31]
## 概要
6行目のコードが消えていなかったので消す

## 具体的にやること

- [x] '.idea/misc.xml'の6行目を削除

## ゴール・目的（完成物の定義）
6行目のコードが消えている

**Comment by nemuki** [comment]
コードブロックになってないのが気になる人になってる

` ← これ

`.idea/misc.xml`

![image](https://user-images.githubusercontent.com/43571743/144413121-1189f45c-da0f-4f38-83c9-57841c404f7b.png)
