### ISSUE TITLE
`services`の中に`OpenWeatherMapService`を追加

### ISSUE THREAD

**Issue by Mitsuki4123** [Sereno-Anan/SerenoAndroidApp#50]

**Comment by nemuki** [comment]
[参考](https://github.com/nemuki/WeatherAndroidApp/blob/main/app/src/main/java/com/nemuki/weatherandroidapp/WeatherService.kt)
これなのでInterfaceでファイル作ると良きね

**Comment by Mitsuki4123** [comment]
ありがとうございます
了解です
