### ISSUE TITLE
`getCurrentWeatherData` 関数を追加

### ISSUE THREAD

**Issue by Mitsuki4123** [Sereno-Anan/SerenoAndroidApp#54]
## 概要

- `getCurrentWeatherData`関数を追加
- GETパラメーターを受け取れるように設定
- レスポンスは `models/openweathermap/currentweatherdata/CurrentWeatherResponce`を使う

**Comment by nemuki** [comment]
ちょっとタイトル長すぎるな

**Comment by nemuki** [comment]
ちょっとタイトル長すぎるな

**Comment by nemuki** [comment]
<img width="630" alt="スクリーンショット 2021-12-04 1 20 07" src="https://user-images.githubusercontent.com/43571743/144636499-755226e8-c7e8-4a3f-befb-54a97ed1e0c2.png">

これのmode以外を追加してもらえると

**Comment by Mitsuki4123** [comment]
了解です
